version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/web/
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15.0-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${NAME}
